sudo: required
language: bash
env:
  global:
  - BUILD_NAME=Test
services:
- docker

before-install:
- openssl aes-256-cbc -K $encrypted_82766e747237_key -iv $encrypted_82766e747237_iv
  -in ./unity3d.alf -out ./Unity_v2019.x.ulf -d
- export UNITY_LICENSE=`cat Unity_v2019.x.ulf`
- rm Unity_v2019.x.ulf
- docker pull $IMAGE_NAME

jobs:
  include:
  - stage: test - editor
    script: "chmod +x ./ci/docker_test.sh && ./ci/docker_test.sh"
    env: TEST_PLATFORM=editmode IMAGE_NAME=unityci/editor:ubuntu-2019.4.19f1-android-0.11.0
    addons:
      artifacts:
        s3_region: "us-west-1"
        paths:
        - "$(pwd)/$TEST_PLATFORM-results.xml"
  - stage: test - play
    script: "chmod +x ./ci/docker_test.sh && ./ci/docker_test.sh"
    env: TEST_PLATFORM=playmode IMAGE_NAME=unityci/editor:ubuntu-2019.4.19f1-android-0.11.0
    addons:
      artifacts:
        s3_region: "us-west-1"
        paths:
        - "$(pwd)/$TEST_PLATFORM-results.xml"
