sudo: required
language: bash
env:
  global:
  - BUILD_NAME=Test
services:
- docker

before_install:
- openssl aes-256-cbc -K $encrypted_6f413a7ac078_key -iv $encrypted_6f413a7ac078_iv -in ci/Unity_v2019.x.ulf.enc -out ci/Unity_v2019.x.ulf -d
- export UNITY_LICENSE=`cat ci/Unity_v2019.x.ulf`
- rm ci/Unity_v2019.x.ulf
- docker pull $IMAGE_NAME

before_script:
- git clone --depth 0 https://github.com/Huchell/PackageCITest.git ../PackageCITest
- mv -rf ./ ../PackageCITest/Packages/com.huchell.test-ci-package/
- cp -rf ../PackageCITest/Packages/com.huchell.test-ci-package/ci/ ci/

jobs:
  include:
  - stage: test - editor
    script: "chmod +x ./ci/docker_test.sh && ./ci/docker_test.sh"
    env: TEST_PLATFORM=editmode IMAGE_NAME=unityci/editor:ubuntu-2019.4.19f1-android-0.11.0
  - stage: test - play
    script: "chmod +x ./ci/docker_test.sh && ./ci/docker_test.sh"
    env: TEST_PLATFORM=playmode IMAGE_NAME=unityci/editor:ubuntu-2019.4.19f1-android-0.11.0
