sudo: required
language: bash
env:
  global:
  - BUILD_NAME=Test
services:
- docker

before-install:
- openssl aes-256-cbc -K $encrypted_6f413a7ac078_key -iv $encrypted_6f413a7ac078_iv -in ci/Unity_v2019.x.ulf.enc -out ci/Unity_v2019.x.ulf -d
- export UNITY_LICENSE=`cat Unity_v2019.x.ulf`
- rm Unity_v2019.x.ulf
- docker pull $IMAGE_NAME

before-script:
- cp -r /project/ci/ /ci/
- git clone https://github.com/Huchell/PackageCITest.git --depth 0
- mv -rf project/ PackageCITest/Packages/project/

jobs:
  include:
  - stage: test - editor
    script: "chmod +x ./ci/docker_test.sh && ./ci/docker_test.sh"
    env: TEST_PLATFORM=editmode IMAGE_NAME=unityci/editor:ubuntu-2019.4.19f1-android-0.11.0
    addons:
      artifacts:
        s3_region: "us-west-1"
        paths:
        - "$(pwd)/$TEST_PLATFORM-results.xml"
  - stage: test - play
    script: "chmod +x ./ci/docker_test.sh && ./ci/docker_test.sh"
    env: TEST_PLATFORM=playmode IMAGE_NAME=unityci/editor:ubuntu-2019.4.19f1-android-0.11.0
    addons:
      artifacts:
        s3_region: "us-west-1"
        paths:
        - "$(pwd)/$TEST_PLATFORM-results.xml"
