name: Unity Package

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]

jobs:   
  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    env:
      UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      
    steps:
      - name: Checkout testbed
        uses: actions/checkout@v2
        with:
          repository: Huchell/PackageCITest
          
      - name: Checkout package
        uses: actions/checkout@v2
        with:
          path: Packages/
          
      - name: Unity - Test runner
        uses: game-ci/unity-test-runner@v2.0-alpha-4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          
