name: post-release

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      version:
        value: ${{ steps.get_version.outputs.version }}
    steps:
      - uses: actions/checkout@v2

      - name: Get version
        id: get_version
        run: |
          echo "::set-output name=version::$(npm --version)"

  tag:
    runs-on: ubuntu-latest
    needs: version
    env:
      VERSION: ${{ needs.version.outputs.version }}
    steps:
      - uses: actions/checkout@v2
      - runs: |
          chmod -x post-release.sh
          sh post-release.sh 
        