name: post-release

on:
  push:
    branches:
      - main
      
  workflow_dispatch:

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get version
        id: get_version
        run: echo "::set-output name=version::$(echo npm --version)" 
        